name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use Node version appropriate for your app

      # Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Clear npm cache (optional but can help)
      - name: Clear npm cache
        run: npm cache clean --force

      # Install gh-pages globally (if not already installed)
      - name: Install gh-pages globally
        run: npm install -g gh-pages

      # Debug: Verify gh-pages installation (this step can help with debugging)
      - name: Verify gh-pages installation
        run: gh-pages --version

      # Build the project (with CI=false to ignore linting errors)
      - name: Build the project
        run: CI=false npm run build

      # Debug: List installed global packages
      - name: Debug: List installed packages
        run: npm list -g --depth=0

      # Deploy the app to GitHub Pages using gh-pages
      - name: Deploy to GitHub Pages
        run: npm run deploy  # Ensure the script uses the locally installed gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
