name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use Node version appropriate for your app

      # Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Clear npm cache (optional but can help)
      - name: Clear npm cache
        run: npm cache clean --force

      # Install gh-pages globally (if not already installed)
      - name: Install gh-pages globally
        run: npm install -g gh-pages

      # Set Git config for deploy (GitHub Actions needs this info)
      - name: Set Git config
        run: |
          git config --global user.email "coogarchallengers@gmail.com"
          git config --global user.name "coogchallengers"
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"

      # Build the project (with CI=false to ignore linting errors)
      - name: Build the project
        run: CI=false npm run build

      # Deploy the app to GitHub Pages using gh-pages
      - name: Deploy to GitHub Pages
        run: npm run deploy  # Ensure the script uses the locally installed gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
